language: bash
sudo: required
services:
  - docker

before_install:
  - docker build --tag=phanect/ossetup .

script:
  - docker run phanect/ossetup /bin/bash -c "curl https://raw.githubusercontent.com/phanect/ossetup/master/setup.sh | bash"
