version: 2

jobs:
  build:
    working_directory: ~/ossetup
    docker:
      - image: kdeneon/all:user-lts
        cmd: ["/bin/bash"]
      - image: kdeneon/all:user
        cmd: ["/bin/bash"]
      - image: phanect/kubuntu:xenial
      - image: phanect/debian-kde
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install --yes git
      - checkout
      - run:
          command: |
            chmod +x ./setup.sh
            ./setup.sh
