version: 2

jobs:
  build-neon:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    machine:
      enabled: true
      environment:
        DEBIAN_FRONTEND: noninteractive
    steps:
      # - setup_remote_docker:
      #    docker_layer_caching: true
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install --yes git

            # TODO install vagrant

            cd .circleci/
            yarn
            git clone --depth=1 https://github.com/KDE/docker-neon-all.git tmp/kdeneon
            node docker2sh.js

            cd tmp/kdeneon
            vagrant up
      - checkout
      - run:
          command: |
            ./setup.sh

  build-debian:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
      SNAPCRAFT_SETUP_CORE: 1
    docker:
      - image: phanect/debian-kde
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          command: |
            apt-get update -qq
            apt-get install --yes git sudo
      - checkout
      - run:
          command: |
            ./setup.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build-neon
      # Debian is now disabled since I don't use Debian for now.
      # Keep commented out for the time I will use Debian again
      - build-debian
