version: 2

jobs:
  build-neon:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: kdeneon/plasma:user
        cmd: ["/bin/bash"]
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install --yes git
      - checkout
      - run: sudo cp ./.circleci/snap.sh /usr/local/bin/snap
      # This process is required to run apm. Atom will be installed via snap,
      # but it can't be tested on CircleCI's Docker container.
      # Instead, apm is installed as deb on CircleCI.
      - run:
          name: Install Atom deb package
          command: |
            sudo apt-get install --yes gconf2 gvfs-bin # Atom's dependencies
            curl --silent --show-error --output /tmp/atom.deb --location "https://atom.io/download/deb"
            sudo dpkg --install /tmp/atom.deb
            sudo apt-get --fix-broken install --yes
      - run:
          command: |
            ./setup.sh

  build-debian:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: debian:buster
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          command: |
            apt-get update -qq
            apt-get install --yes git sudo
      - checkout
      - run:
          command: |
            ./setup.sh

  build-debian-wsl:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: debian:stretch
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          command: |
            apt-get update -qq
            apt-get install --yes git sudo
      - checkout
      - run:
          command: |
            ./setup.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build-neon
      - build-debian
      - build-debian-wsl
