version: 2

jobs:
  build-neon:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: kdeneon/all:user
        cmd: ["/bin/bash"]
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install --yes git
      - checkout
      - run:
          command: |
            ./setup.sh

  build-debian:
    working_directory: ~/ossetup
    environment:
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: phanect/debian-kde
        environment:
          DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          command: |
            apt-get update -qq
            apt-get install --yes git sudo
      - checkout
      - run:
          command: |
            ./setup.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build-neon
      # Debian is now disabled since I don't use Debian for now.
      # Keep commented out for the time I will use Debian again
      # - build-debian
